#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import argparse
from photos.prototype import *

console = Console(
    __package__,
    'config/settings.json',
    [
        'config/repository.xml',
        'config/service.xml',
        'config/command.xml',
    ]
)

console.activate()