#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
import argparse
from photos.prototype import *

base_path = os.path.dirname(os.path.abspath(__file__))

def __p(path):
    return os.path.join(base_path, path)

if base_path not in sys.path:
    sys.path.append(base_path)

console = Console(
    __package__,
    __p('config/settings.json'),
    [
        __p('config/repository.xml'),
        __p('config/service.xml'),
        __p('config/command.xml'),
    ]
)

console.activate()
